

```{r}
library(lme4)
library(tidyverse)
library(car)
library(ggplot2)
library(broom)
library(emmeans)
library(ggpubr)
library(caret)
library(knitr)
library(glue)
library(ggplot2)
library(ggpmisc)
library(ggrepel)

```


```{r}


df <- read.csv("Folder2-MCMC_Outputs/model_MCMC_statistics.csv" )
df <- df[seq(1, nrow(df), by = 2), ]
viruses <- df$Virus

df$X2.5..Quantile <- 1 - df$X2.5..Quantile
df$X97.5..Quantile <- 1 - df$X97.5..Quantile
df$Mean <- (df$X97.5..Quantile + df$X2.5..Quantile)/2

```



```{r}

genome_lengths <- c(11161, 15894 ,15638 ,15462, 15246 , 15384, 18959, 19114, 15191)
mean_pros = df$Mean
ci_width <- df$X2.5..Quantile - df$X97.5..Quantile  

weights <- ci_width / 2

```


```{r}

df <- data.frame(genome_lengths,mean_pros)
df <- df[order(df$mean_pros),]
mod_gn <- lm(mean_pros~genome_lengths, data=df)
performance::check_model(mod_gn, check="linearity")
performance::check_model(mod_gn, check="homogeneity")
performance::check_model(mod_gn, check="qq")
## no apparent violations of assumptions
tidy(mod_gn, conf.int=TRUE, conf.level=0.95)

```


```{r}
# show the average number of base pairs traversed
1/mean_pros
```


```{r}
viruses
```


```{r}
summary(mod_gn)
```



```{r}

viruses <- c("VSV", "MeV", "PIV2", "PIV3", "PIV5", "MuV", "EBOV", "MV","RSV")
df <- df[order(rownames(df)),]
g_df <- ggplot(df, aes(x=genome_lengths, y=mean_pros)) + 
  theme_bw() +
  geom_point() + geom_errorbar(aes(ymin = mean_pros-weights, ymax = mean_pros+weights), width = 400) +
  ylab(expression("P"["off"])) +
  xlab("Genome Length (bases)") +
  geom_smooth(method="lm", se=FALSE) +
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
               label.x.npc = "right", label.y.npc = 0.9, 
               formula = y ~ x, parse = TRUE, size = 6) +
   xlim(10000, max(df$genome_lengths) + 1000) +  
  ylim(0, .0004) +  
  geom_text_repel(aes(label = viruses), size = 4) +  # Annotating each dot
  theme(
    axis.title.x = element_text(size = 16),  # Axis title size for X
    axis.title.y = element_text(size = 16),  # Axis title size for Y
    axis.text.x = element_text(size = 16),   # Tick label size for X
    axis.text.y = element_text(size = 16)    # Tick label size for Y
  )
ggsave("Figures/Fig3/linear_regression.svg", plot = g_df, width = 6, height = 4, device = "svg")
g_df

```

